name: Deploy to GitHubPages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy with gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: src
