name: Validate with W3CValidator
on:
  push:
    branches:
      - main

jobs:
  validate:
    name: Deploy with gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: W3CValidator
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: src/
          css: true
